spring:
  batch:
    job:
      enabled: ${spring.batch.job.names:NONE}
      names: ${job.name:NONE}
    #      enabled: ${job.name:NONE}
    jdbc:
      initialize-schema: never
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:23306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: test1357
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      data-locations:
        - classpath:member.sql
      schema-locations:
        - classpath:schema.sql
batch:
  initialize-schema: always
